### ISSUE TITLE
error on run demo.js

### ISSUE THREAD

**Issue by lclms** [JarvisFT/vodafone-controller#1]
when I run demo.js this error appears. any suggestion?

MBP-de-Luis:vodafone-controller luislima$ node demo.js 
UDP socket listening on 0.0.0.0:8082
UNKNOWN
UNKNOWN
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.1.67:8082
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)

**Comment by FehTeh** [comment]
Hi,

is 192.168.1.67 your set-top box ip? 

Try this on the command line:

netcat 192.168.1.67 8082 - the box should response with a Hello

**Comment by lclms** [comment]
hello,
the box is an ARRIS
I did a telnet command to that port and it returns

telnet 192.168.1.67 8082
Trying 192.168.1.67...
telnet: Unable to connect to remote host: Connection refused

any suggestion?
